### ISSUE TITLE
Error in PDF export in ej2-ng-charts version 16.2.50

### ISSUE THREAD

**Issue by adnanebrahimi** [syncfusion/ej2-ng-charts#5]
After Changing package manager to yarn and update project this error occurs:

`ERROR in node_modules/@syncfusion/ej2-pdf-export/src/interfaces/i-pdf-writer.d.ts(28,55): error TS2304: Cannot find name 'GLbyte'.`

**Comment by karthik-chan** [comment]
The issue with "After Changing package manager to yarn and update project this error occurs: `ERROR in node_modules/@syncfusion/ej2-pdf-export/src/interfaces/i-pdf-writer.d.ts(28,55): error TS2304: Cannot find name 'GLbyte'.` has been fixed. To overcome this issue, please update the @syncfusion/ej2-pdf-export npm package into V16.3.27 and above.
